### ISSUE TITLE
Product doesn't work

### ISSUE THREAD

**Issue by oliver-daniel** [Mystery3051/uoft-autorenew#1]
**How to reproduce:**
1. Clone repo from master.
2. Try to run program.

My Bookstore goods are still not auto-renewed, and now Meric is standing outside my house with a boombox and crying very loudly.
Looking over the source, thus may have to do with the fact that this branch doesn't have any code in it. Granted, this could also be a CORS problem or something. Yeah, that's probably it. CORS is the source of most problems.

**Comment by alex-kozin** [comment]
This is an expected behaviour.
